name: Deploy to Staging
env:
  NAMESPACE: development
  REPO: crimsyfrontend/ng-frontend

on:
  push:
    branches:
      - develop

jobs:
  docker:
    name: Publish to Docker Registry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache node app cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Install Dependencies
        run: npm install
      - name: Build Angular App
        run: ng build
      - name: Docker Login
        run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - name: Build Docker image
        run: docker build -t ${REPO}:${GITHUB_RUN_ID} .
      - name: Publish Docker image
        run: docker push ${REPO}:${GITHUB_RUN_ID}
  deploy:
    name: deploy to cluster
    needs: [docker]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: deploy to cluster
        uses: docker://nickgronow/kubectl
        with:
          config_data: ${{ secrets.KUBE_CONFIG }}
          args: set image --record deployment/frontend frontend=${REPO}:${GITHUB_RUN_ID} -n ${NAMESPACE}
      - name: verify deployment
        uses: docker://nickgronow/kubectl
        with:
          config_data: ${{ secrets.KUBE_CONFIG }}
          args: '"rollout status deployment/frontend -n ${NAMESPACE}"'

